// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Yx8kae3DRncRtgJRi8b4vhgtTUyBpdo',
    appId: '1:1039278519261:web:e108136d7b9047a3387c34',
    messagingSenderId: '1039278519261',
    projectId: 'coba4-a9c92',
    authDomain: 'coba4-a9c92.firebaseapp.com',
    storageBucket: 'coba4-a9c92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcfRCBY_y6n6jbSWKE4o8TlHje_xP9ryw',
    appId: '1:1039278519261:android:c87c921c8147b51f387c34',
    messagingSenderId: '1039278519261',
    projectId: 'coba4-a9c92',
    storageBucket: 'coba4-a9c92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmgU4eFOMa4HDOqyEuIP2js8irSz9Jv4I',
    appId: '1:1039278519261:ios:171f29823f08aadd387c34',
    messagingSenderId: '1039278519261',
    projectId: 'coba4-a9c92',
    storageBucket: 'coba4-a9c92.appspot.com',
    iosBundleId: 'com.example.coba4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmgU4eFOMa4HDOqyEuIP2js8irSz9Jv4I',
    appId: '1:1039278519261:ios:171f29823f08aadd387c34',
    messagingSenderId: '1039278519261',
    projectId: 'coba4-a9c92',
    storageBucket: 'coba4-a9c92.appspot.com',
    iosBundleId: 'com.example.coba4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Yx8kae3DRncRtgJRi8b4vhgtTUyBpdo',
    appId: '1:1039278519261:web:a76d3a70acd9796a387c34',
    messagingSenderId: '1039278519261',
    projectId: 'coba4-a9c92',
    authDomain: 'coba4-a9c92.firebaseapp.com',
    storageBucket: 'coba4-a9c92.appspot.com',
  );
}
